ITEM_TYPE_DATA = {
	"Crude Bow": "weapon2h",
	"Short Bow": "weapon2h",
	"Long Bow": "weapon2h",
	"Composite Bow": "weapon2h",
	"Recurve Bow": "weapon2h",
	"Bone Bow": "weapon2h",
	"Royal Bow": "weapon2h",
	"Death Bow": "weapon2h",
	"Grove Bow": "weapon2h",
	"Decurve Bow": "weapon2h",
	"Compound Bow": "weapon2h",
	"Sniper Bow": "weapon2h",
	"Ivory Bow": "weapon2h",
	"Highborn Bow": "weapon2h",
	"Decimation Bow": "weapon2h",
	"Thicket Bow": "weapon2h",
	"Citadel Bow": "weapon2h",
	"Ranger Bow": "weapon2h",
	"Maraketh Bow": "weapon2h",
	"Chimeric Bow": "weapon2h",
	"Imperial Bow": "weapon2h",
	"Armageddon Bow": "weapon2h",
	"Gnarled Branch": "weapon2h",
	"Primitive Staff": "weapon2h",
	"Long Staff": "weapon2h",
	"Iron Staff": "weapon2h",
	"Coiled Staff": "weapon2h",
	"Royal Staff": "weapon2h",
	"Vile Staff": "weapon2h",
	"Woodful Staff": "weapon2h",
	"Quarterstaff": "weapon2h",
	"Military Staff": "weapon2h",
	"Serpentine Staff": "weapon2h",
	"Highborn Staff": "weapon2h",
	"Foul Staff": "weapon2h",
	"Primordial Staff": "weapon2h",
	"Lathi": "weapon2h",
	"Ezoymte Staff": "weapon2h",
	"Maelström Staff": "weapon2h",
	"Maelstrom Staff": "weapon2h",
	"Imperial Staff": "weapon2h",
	"Damnation Staff": "weapon2h",
	"Stone Axe": "weapon2h",
	"Jade Chopper": "weapon2h",
	"Woodsplitter": "weapon2h",
	"Poleaxe": "weapon2h",
	"Double Axe": "weapon2h",
	"Gilded Axe": "weapon2h",
	"Shadow Axe": "weapon2h",
	"Jasper Chopper": "weapon2h",
	"Timber Axe": "weapon2h",
	"Headsman Axe": "weapon2h",
	"Labrys": "weapon2h",
	"Noble Axe": "weapon2h",
	"Abyssal Axe": "weapon2h",
	"Karui Chopper": "weapon2h",
	"Sundering Axe": "weapon2h",
	"Ezomyte Axe": "weapon2h",
	"Vaal Axe": "weapon2h",
	"Despot Axe": "weapon2h",
	"Void Axe": "weapon2h",
	"Driftwood Maul": "weapon2h",
	"Tribal Maul": "weapon2h",
	"Mallet": "weapon2h",
	"Sledgehammer": "weapon2h",
	"Spiked Maul": "weapon2h",
	"Brass Maul": "weapon2h",
	"Fright Maul": "weapon2h",
	"Totemic Maul": "weapon2h",
	"Great Mallet": "weapon2h",
	"Steelhead": "weapon2h",
	"Spiny Maul": "weapon2h",
	"Plated Maul": "weapon2h",
	"Dread Maul": "weapon2h",
	"Karui Maul": "weapon2h",
	"Colossus Mallet": "weapon2h",
	"Piledriver": "weapon2h",
	"Meatgrinder": "weapon2h",
	"Imperial Maul": "weapon2h",
	"Terror Maul": "weapon2h",
	"Corroded Blade": "weapon2h",
	"Long Sword": "weapon2h",
	"Bastard Sword": "weapon2h",
	"Two-Handed Sword": "weapon2h",
	"Etched Greatsword": "weapon2h",
	"Ornate Sword": "weapon2h",
	"Spectral Sword": "weapon2h",
	"Butcher Sword": "weapon2h",
	"Footman Sword": "weapon2h",
	"Highland Blade": "weapon2h",
	"Engraved Greatsword": "weapon2h",
	"Tiger Sword": "weapon2h",
	"Wraith Sword": "weapon2h",
	"Headman's Sword": "weapon2h",
	"Reaver Sword": "weapon2h",
	"Ezomyte Blade": "weapon2h",
	"Vaal Greatsword": "weapon2h",
	"Lion Sword": "weapon2h",
	"Infernal Sword": "weapon2h",
	"Nailed Fist": "weapon1h",
	"Sharktooth Claw": "weapon1h",
	"Awl": "weapon1h",
	"Cat's Paw": "weapon1h",
	"Blinder": "weapon1h",
	"Timeworn Claw": "weapon1h",
	"Sparkling Claw": "weapon1h",
	"Fright Claw": "weapon1h",
	"Thresher Claw": "weapon1h",
	"Gouger": "weapon1h",
	"Tiger's Paw": "weapon1h",
	"Gut Ripper": "weapon1h",
	"Prehistoric Claw": "weapon1h",
	"Noble Claw": "weapon1h",
	"Dread Claw": "weapon1h",
	"Great White Claw": "weapon1h",
	"Throat Stabber": "weapon1h",
	"Hellion's Paw": "weapon1h",
	"Eye Gouger": "weapon1h",
	"Vaal Claw": "weapon1h",
	"Imperial Claw": "weapon1h",
	"Terror Claw": "weapon1h",
	"Glass Shank": "weapon1h",
	"Skinning Knife": "weapon1h",
	"Carving Knife": "weapon1h",
	"Stiletto": "weapon1h",
	"Boot Knife": "weapon1h",
	"Copper Kris": "weapon1h",
	"Skean": "weapon1h",
	"Imp Dagger": "weapon1h",
	"Flaying Knife": "weapon1h",
	"Butcher Knife": "weapon1h",
	"Poinard": "weapon1h",
	"Boot Blade": "weapon1h",
	"Golden Kris": "weapon1h",
	"Royal Skean": "weapon1h",
	"Fiend Dagger": "weapon1h",
	"Gutting Knife": "weapon1h",
	"Slaughter Knife": "weapon1h",
	"Ambusher": "weapon1h",
	"Ezomyte Dagger": "weapon1h",
	"Platinum Kris": "weapon1h",
	"Imperial Skean": "weapon1h",
	"Demon Dagger": "weapon1h",
	"Rusted Hatchet": "weapon1h",
	"Jade Hatchet": "weapon1h",
	"Boarding Axe": "weapon1h",
	"Cleaver": "weapon1h",
	"Broad Axe": "weapon1h",
	"Arming Axe": "weapon1h",
	"Gilded Axe": "weapon1h",
	"Spectral Axe": "weapon1h",
	"Jasper Axe": "weapon1h",
	"Tomahawk": "weapon1h",
	"Wrist Chopper": "weapon1h",
	"War Axe": "weapon1h",
	"Chest Splitter": "weapon1h",
	"Ceremonial Axe": "weapon1h",
	"Wraith Axe": "weapon1h",
	"Karui Axe": "weapon1h",
	"Siege Axe": "weapon1h",
	"Reaver Axe": "weapon1h",
	"Ezomyte Axe": "weapon1h",
	"Vaal Hatchet": "weapon1h",
	"Royal Axe": "weapon1h",
	"Infernal Axe": "weapon1h",
	"Driftwood Club": "weapon1h",
	"Tribal Club": "weapon1h",
	"Spiked Club": "weapon1h",
	"Stone Hammer": "weapon1h",
	"War Hammer": "weapon1h",
	"Bladed Mace": "weapon1h",
	"Ceremonial Mace": "weapon1h",
	"Dream Mace": "weapon1h",
	"Petrified Club": "weapon1h",
	"Barbed Club": "weapon1h",
	"Rock Breaker": "weapon1h",
	"Battle Hammer": "weapon1h",
	"Flanged Mace": "weapon1h",
	"Ornate Mace": "weapon1h",
	"Phantom Mace": "weapon1h",
	"Ancestral Club": "weapon1h",
	"Tenderizer": "weapon1h",
	"Gavel": "weapon1h",
	"Legion Hammer": "weapon1h",
	"Pernarch": "weapon1h",
	"Auric Mace": "weapon1h",
	"Nightmare Mace": "weapon1h",
	"Rusted Sword": "weapon1h",
	"Copper Sword": "weapon1h",
	"Sabre": "weapon1h",
	"Broad Sword": "weapon1h",
	"War Sword": "weapon1h",
	"Ancient Sword": "weapon1h",
	"Elegant Sword": "weapon1h",
	"Dusk Blade": "weapon1h",
	"Variscite Blade": "weapon1h",
	"Cutlass": "weapon1h",
	"Baselard": "weapon1h",
	"Battle Sword": "weapon1h",
	"Elder Sword": "weapon1h",
	"Graceful Sword": "weapon1h",
	"Twilight Blade": "weapon1h",
	"Gemstone Sword": "weapon1h",
	"Corsair Sword": "weapon1h",
	"Gladius": "weapon1h",
	"Legion Sword": "weapon1h",
	"Vaal Blade": "weapon1h",
	"Eternal Sword": "weapon1h",
	"Midnight Blade": "weapon1h",
	"Driftwood Sceptre": "weapon1h",
	"Darkwood Sceptre": "weapon1h",
	"Bronze Sceptre": "weapon1h",
	"Quartz Sceptre": "weapon1h",
	"Iron Sceptre": "weapon1h",
	"Ochre Sceptre": "weapon1h",
	"Ritual Sceptre": "weapon1h",
	"Shadow Sceptre": "weapon1h",
	"Grinning Fetish": "weapon1h",
	"Sekhem": "weapon1h",
	"Crystal Sceptre": "weapon1h",
	"Lead Sceptre": "weapon1h",
	"Blood Sceptre": "weapon1h",
	"Royal Sceptre": "weapon1h",
	"Abyssal Sceptre": "weapon1h",
	"Karui Sceptre": "weapon1h",
	"Tyrant's Sekhem": "weapon1h",
	"Opal Sceptre": "weapon1h",
	"Platinum Sceptre": "weapon1h",
	"Carnal Sceptre": "weapon1h",
	"Vaal Sceptre": "weapon1h",
	"Void Sceptre": "weapon1h",
	"Rusted Spike": "weapon1h",
	"Whalebone Rapier": "weapon1h",
	"Battered Foil": "weapon1h",
	"Basket Rapier": "weapon1h",
	"Jagged Foil": "weapon1h",
	"Antique Rapier": "weapon1h",
	"Elegant Foil": "weapon1h",
	"Thorn Rapier": "weapon1h",
	"Wyrmbone Rapier": "weapon1h",
	"Burnished Foil": "weapon1h",
	"Estoc": "weapon1h",
	"Serrated Foil": "weapon1h",
	"Primeval Rapier": "weapon1h",
	"Fancy Foil": "weapon1h",
	"Apex Rapier": "weapon1h",
	"Dragonbone Rapier": "weapon1h",
	"Tempered Foil": "weapon1h",
	"Pecoraro": "weapon1h",
	"Spiraled Foil": "weapon1h",
	"Vaal Rapier": "weapon1h",
	"Jeweled Foil": "weapon1h",
	"Harpy Rapier": "weapon1h",
	"Driftwood Wand": "weapon1h",
	"Goat's Horn": "weapon1h",
	"Carved Wand": "weapon1h",
	"Quartz Wand": "weapon1h",
	"Spiraled Wand": "weapon1h",
	"Sage Wand": "weapon1h",
	"Faun's Horn": "weapon1h",
	"Engraved Wand": "weapon1h",
	"Crystal Wand": "weapon1h",
	"Serpent Wand": "weapon1h",
	"Omen Wand": "weapon1h",
	"Demon's Horn": "weapon1h",
	"Imbued Wand": "weapon1h",
	"Opal Wand": "weapon1h",
	"Tornado Wand": "weapon1h",
	"Prophecy Wand": "weapon1h",
	"Plate Vest": "chest",
	"Banded Vest": "chest",
	"Leather Armour": "chest",
	"Robe": "chest",
	"Chestplate": "chest",
	"Ringmail Vest": "chest",
	"Quilted Leather": "chest",
	"Scale Cuirass": "chest",
	"Strapped Leathers": "chest",
	"Brass Plate": "chest",
	"Arcanist Vest": "chest",
	"Hardened Chainmail": "chest",
	"Leather Tunic": "chest",
	"Toughened Leather": "chest",
	"Banded Armour": "chest",
	"Mammoth Plate": "chest",
	"Ringmail": "chest",
	"Caster Robe": "chest",
	"Quilted Armour": "chest",
	"Scale Hauberk": "chest",
	"Leather Jerkin": "chest",
	"Arcanist Armor": "chest",
	"Plated Chainmail": "chest",
	"Sunplate": "chest",
	"Commander Leather": "chest",
	"Duelist Cuirass": "chest",
	"Heavy Strapped Leathers": "chest",
	"Arena Plate": "chest",
	"Diplomatic Robe": "chest",
	"Holy Cloth": "chest",
	"Ribcage": "chest",
	"Plated Vest": "chest",
	"Gladiator Hauberk": "chest",
	"Inquisitor Armour": "chest",
	"Gladiator Armour": "chest",
	"Arcanist Vestment": "chest",
	"Full Ringmail": "chest",
	"Bone Armour": "chest",
	"Imperial Scales": "chest",
	"Full Strapped Leathers": "chest",
	"Imperial Plate": "chest",
	"Arcane Robes": "chest",
	"Heavy Chainmail": "chest",
	"Imperial Tunic": "chest",
	"Reinforced Leather Armour": "chest",
	"Demonguard Hauberk": "chest",
	"Rhino Plate": "chest",
	"Golden Plate": "chest",
	"Powerweaver Shroud": "chest",
	"Red Spiderhide": "chest",
	"Spined Armour": "chest",
	"Studded Vest": "chest",
	"Silken Robe": "chest",
	"Armadillo Carapace": "chest",
	"Ringmail Jacket": "chest",
	"Imposing Tunic": "chest",
	"Plated Tunic": "chest",
	"Hardened Leather": "chest",
	"Armadillo Skin Jacket": "chest",
	"Bladed Armour": "chest",
	"Stately Vest": "chest",
	"Razor Chainmail": "chest",
	"Ancient Shroud": "chest",
	"Belted Pixane": "chest",
	"Lamellar Armour": "chest",
	"Lithe Tunic": "chest",
	"Regal Plate": "chest",
	"Ancient Carapace": "chest",
	"Regal Tunic": "chest",
	"Rock Shell": "chest",
	"Grand Inquisitor Armour": "chest",
	"Majestic Plate": "chest",
	"Grand Robes": "chest",
	"Moonplate": "chest",
	"Woolen Tunic": "chest",
	"Woven Behterets": "chest",
	"Weathered Doublet": "chest",
	"Disc Armour": "chest",
	"Jagged Plate": "chest",
	"Withered Shroud": "chest",
	"Wizened Robes": "chest",
	"Splinted Armour": "chest",
	"Scaly Hauberk": "chest",
	"Stealth Tunic": "chest",
	"Weathered Vest": "chest",
	"Hardened Carapace": "chest",
	"Plated Robe": "chest",
	"Skeletal Plate": "chest",
	"Spined Jerkin": "chest",
	"Painted Tunic": "chest",
	"Banded Behterets": "chest",
	"Studded Battleplate": "chest",
	"Ringmail Coat": "chest",
	"Skeletal Cage": "chest",
	"Full Skeletal Armour": "chest",
	"Mirror Armour": "chest",
	"Venerable Carapace": "chest",
	"Chaos Plate": "chest",
	"Saintly Robes": "chest",
	"Brigandine": "chest",
	"Iron Greaves": "feet",
	"Wool Boots": "feet",
	"Chainmail Boots": "feet",
	"Wrapped Boots": "feet",
	"Leatherscale Boots": "feet",
	"Rawhide Boots": "feet",
	"Velvet Boots": "feet",
	"Plated Greaves": "feet",
	"Deerskin Boots": "feet",
	"Ringmail Boots": "feet",
	"Strapped Boots": "feet",
	"Ironscale Boots": "feet",
	"Silk Boots": "feet",
	"Nubuck Boots": "feet",
	"Ancient Greaves": "feet",
	"Clasped Boots": "feet",
	"Zealot Boots": "feet",
	"Platescale Boots": "feet",
	"Embroidered Boots": "feet",
	"Regal Greaves": "feet",
	"Slink Boots": "feet",
	"Shackled Boots": "feet",
	"Destroyer Greaves": "feet",
	"Swiftsteel Treads": "feet",
	"Caster Boots": "feet",
	"Snakeskin Treads": "feet",
	"Champion Treads": "feet",
	"Graveyard Treads": "feet",
	"Iron Gauntlets": "hands",
	"Rawhide Gloves": "hands",
	"Wool Gloves": "hands",
	"Ironscale Gloves": "hands",
	"Wrapped Gloves": "hands",
	"Chainmail Gloves": "hands",
	"Deerskin Gloves": "hands",
	"Plated Gauntlets": "hands",
	"Velvet Gloves": "hands",
	"Bronzescale Gloves": "hands",
	"Strapped Gloves": "hands",
	"Ringmail Gloves": "hands",
	"Nubuck Gloves": "hands",
	"Ancient Gauntlets": "hands",
	"Silk Gloves": "hands",
	"Platescale Gloves": "hands",
	"Clasped Gloves": "hands",
	"Slink Gloves": "hands",
	"Zealot Gloves": "hands",
	"Regal Gauntlets": "hands",
	"Embroided Gloves": "hands",
	"Riveted Gauntlets": "hands",
	"Destroyer Gloves": "hands",
	"Moonlight Gloves": "hands",
	"Moire Handshrouds": "hands",
	"Shagreen Vambraces": "hands",
	"Jaconet Grips": "hands",
	"Rusted Casque": "head",
	"Felt Cap": "head",
	"Rusted Helmet": "head",
	"Vine Circlet": "head",
	"Rusted Mask": "head",
	"Rusted Chain Cap": "head",
	"Copper Circlet": "head",
	"Tribal Mask": "head",
	"Leather Cap": "head",
	"Executioner Casque": "head",
	"Chain Cap": "head",
	"Flanged Helmet": "head",
	"Tribal Circlet": "head",
	"Copper Mask": "head",
	"Gladiator Casque": "head",
	"Leather Hood": "head",
	"Crusader Helmet": "head",
	"Ribbed Helmet": "head",
	"Gemmed Circlet": "head",
	"Crusader Casque": "head",
	"Studded Hood": "head",
	"Gilded Chain Helmet": "head",
	"Ritual Mask": "head",
	"Gilded Helmet": "head",
	"Gilded Circlet": "head",
	"Imperial Casque": "head",
	"Decadent Mask": "head",
	"Harpy Crown": "head",
	"Cadaver Mask": "head",
	"Mage Miter": "head",
	"Destroyer Crown": "head",
	"Brawler Helm": "head",
	"Teutonic Helm": "head",
	"Plain Buckler": "shield",
	"Salvaged Wall Shield": "shield",
	"Tribal Armguard": "shield",
	"Tribal Kite Shield": "shield",
	"Tribal Buckler": "shield",
	"Salvaged Shield": "shield",
	"Tribal Wall Shield": "shield",
	"Bone Focus": "shield",
	"Rustic Armguard": "shield",
	"Bronze Buckler": "shield",
	"Reinforced Kite Shield": "shield",
	"Etched Shield": "shield",
	"Iron Wall Shield": "shield",
	"Tribal Focus": "shield",
	"Reinforced Buckler": "shield",
	"Crusaders Kite Shield": "shield",
	"Imperial Shield": "shield",
	"Leather Armguard": "shield",
	"Steel Buckler": "shield",
	"Vine Focus": "shield",
	"Etched Wall Shield": "shield",
	"Bladed Shield": "shield",
	"Engraved Buckler": "shield",
	"Steel Kite Shield": "shield",
	"Steel Armguard": "shield",
	"Gilded Buckler": "shield",
	"Ornate Focus": "shield",
	"Ornate Wall Shield": "shield",
	"Eternal Focus": "shield",
	"Immortal Armguard": "shield",
	"Templar Shield": "shield",
	"Cavalier Shield": "shield",
	"Reaver Shield": "shield",
	"Hunting Shield": "shield",
	"Portrait Shield": "shield",
	"Sigil Kite Shield": "shield",
	"Ornate Armguard": "shield"
};